name: Version or Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

permissions: read-all

jobs:
  release:
    if: ${{ github.repository_owner == 'acacode' }}
    permissions:
      contents: write # to create release
      id-token: write # to generate provenance and oidc token
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set-up Mise
        uses: jdx/mise-action@be3be2260bc02bc3fbf94c5e2fed8b7964baf074 # v3.4.0
        with:
          cache: false
      - run: yarn install --immutable
      - name: Create Release Pull Request
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: yarn changeset version
          publish: yarn npm publish --tolerate-republish
        env:
          GITHUB_TOKEN: ${{ github.token }}
