name: Version or Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

permissions: read-all

jobs:
  release:
    if: ${{ github.repository_owner == 'acacode' }}
    permissions:
      contents: write # to create release
      id-token: write # to generate provenance and oidc token
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set-up Mise
        uses: jdx/mise-action@c53b9236f0b3370f31520f8b142f141256d839c6 # v3.6.0
        with:
          cache: false
      - run: yarn install --immutable
      - name: Create Release Pull Request
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: yarn changeset version
          publish: yarn npm publish --tolerate-republish
        env:
          GITHUB_TOKEN: ${{ github.token }}
