name: Version or Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

permissions: read-all

jobs:
  release:
    if: ${{ github.repository_owner == 'acacode' }}
    permissions:
      contents: write # to create release
      id-token: write # to generate provenance and oidc token
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set-up Mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          cache: false
      - run: yarn install --immutable
      - name: Create Release Pull Request
        uses: changesets/action@c48e67d110a68bc90ccf1098e9646092baacaa87 # v1.6.0
        with:
          version: yarn changeset version
          publish: yarn npm publish --tolerate-republish
        env:
          GITHUB_TOKEN: ${{ github.token }}
