name: Version or Publish

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}

permissions: read-all

jobs:
  release:
    if: ${{ github.repository_owner == 'acacode' }}
    permissions:
      contents: write # to create release
      id-token: write # to generate provenance and oidc token
      issues: write # to post issue comments
      pull-requests: write # to create pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Set-up Mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3.5.1
        with:
          cache: false
      - run: yarn install --immutable
      - name: Create Release Pull Request
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          version: yarn changeset version
          publish: yarn npm publish --tolerate-republish
        env:
          GITHUB_TOKEN: ${{ github.token }}
